Adding title check

diff --git a/.github/workflows/pr_review.yml b/.github/workflows/pr_review.yml
--- a/.github/workflows/pr_review.yml
+++ b/.github/workflows/pr_review.yml
@@ -12,8 +12,15 @@ jobs:
         env:
           DESCRIPTION: ${{ github.event.pull_request.body }}
           COMMIT_COUNT: ${{ github.event.pull_request.commits }}
+          TITLE: ${{ github.event.pull_request.title }}
         run: |
           failed=0
+          if ! [[ $TITLE =~ ^[\w]{4}-[\d]+ - .*$ ]]; then
+            echo "Please update the Title to match the form: [Ticket Prefix]-[Ticket Number] - [Description]."
+            echo "E.g. LCAM-1234 - Fixes fatal error"
+            failed=1
+          fi
+          
           if [[ $DESCRIPTION == *"Describe what you did and why"* ]]; then
             echo "Please add a meaningful description to your PR."
             failed=1
